apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-heimdall-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      containers:
      - name: heimdall-container
        image: mpifrpsr/heimdall
        args: ["-H", "rabbitmq-service", "-p", "5672","--input", "paf-heimdall-input",
                "--success", "paf-heimdall-success", "--fail", "paf-heimdall-fail" ]
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
        volumeMounts:
        - mountPath: /beegfsEDD/PAF/PAF/RESULTS
          name: heimdall-outputs-volume
        - mountPath: /beegfsEDD/PAF/PAF/SEARCH
          name: heimdall-inputs-volume
          readOnly: true
      volumes:
      - name: heimdall-outputs-volume
        hostPath:
          path: /beegfsEDD/PAF/PAF/RESULTS
          type: Directory
      - name: heimdall-inputs-volume
        hostPath:
          path: /beegfsEDD/PAF/PAF/SEARCH
          type: Directory
