apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-heimdall-interactive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall-interactive
  template:
    metadata:
      labels:
        app: heimdall-interactive
    spec:
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      containers:
      - name: heimdall-container
        image: mpifrpsr/heimdall
        imagePullPolicy: Always
        command: ['bash']
        stdin: true
        tty: true
        volumeMounts:
        #- mountPath: /beegfs/heimpaf/
        #  name: heimdall-outputs-volume
        - mountPath: /beegfsEDD/PAF/PAF/RESULTS/
          name: heimdall-outputs-volume
        #- mountPath: /beegfs/PAFJUNE/
        #  name: heimdall-inputs-volume
        - mountPath: /beegfsEDD/PAF/PAF/SEARCH/
          name: heimdall-inputs-volume
        - mountPath: /beegfs/PAFAUG/
          name: heimdall-inputs-volume2
          readOnly: true
      volumes:
      - name: heimdall-outputs-volume
        hostPath:
          #path: /beegfs/heimpaf/
          path: /beegfsEDD/PAF/PAF/RESULTS/
          type: Directory
      - name: heimdall-inputs-volume
        hostPath:
          #path: /beegfs/PAFJUNE/
          path: /beegfsEDD/PAF/PAF/SEARCH/
          type: Directory
      - name: heimdall-inputs-volume2
        hostPath:
          path: /beegfs/PAFAUG/
          type: Directory
