apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-heimdall-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      containers:
      - name: heimdall-container
        image: mpifrpsr/heimdall
        args: ["-H", "rabbitmq-service", "-p", "5672"]
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
        volumeMounts:
        - mountPath: /beegfs/heimpaf/
          name: heimdall-volume
      volumes:
      - name: heimdall-volume
        hostPath:
          path: /beegfs/heimpaf/
          type: Directory
